package org.hungrycapybara.ordersimulator

import cats.effect.IO
import org.hungrycapybara.ordersimulator.model.ExecutionEnvironment
import slick.jdbc.SQLiteProfile.api.Database

trait EventGenerator:
  def run(executionEnv: ExecutionEnvironment, database: Database): IO[Unit]

  /**
    * Helper method to emit a single event generated by the provided IO action. This can be used by individual event generators to emit events in a consistent way, including logging the generated event.
    *
    * @param generateEvent The IO action that generates the event.
    * Usage example:
    * {{{
    * def emit(): IO[Unit] = emitOne(IO.delay(randomCustomerProfileEvent()))
    * }}}
    */
  // def emitOne[T](generateEvent: IO[T]): IO[Unit] =
  //   generateEvent
  //     .flatMap(event => IO.println(s"Generated event: $event"))
